### ISSUE TITLE
Confusing invocation

### ISSUE THREAD

**Issue by Tursko** [NicoWeio/Alexa-Spotify-Remote#3]
Firstly, the skill does successfully control my remote spotify devices but it seems to lose context easily.

Example of what I'm currently doing (please correct me if I'm missing something).

"Alexa open playback control"
"Alexa next song"
*next song plays
"Alexa next song"
*That command is not supported right now

Do I have to launch playback control every time? I've even tried "Alexa ask playback control to go to next song" and that doesn't work.

**Comment by NicoWeio** [comment]
Indeed, keeping context isn't easy. I considered some improvements in #1, but won't have time to work on these for at least a month.

> I've even tried "Alexa ask playback control to go to next song" and that doesn't work.
That should definitely work. How did Alexa respond in that case?

**Comment by Tursko** [comment]
Okay I'll close this issue then. So for now I'll have to always 'open' the skill with "Alexa open playback control"?

I feel like a basic work around would be  "Alexa ask playback control to go to next song". Not perfect but it saves a bit of time.
**Edit**: Actually I see that it does work that way. That actually works perfectly fine.
